name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: [enhancement]
assignees:
  - chiefmikey
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature you'd like
      description: Include a clear and concise description of what you want to happen.
      placeholder: ex. A potential feature could be [...]
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: Is your feature request related to a problem?
      description: Include a clear and concise description of what the problem is.
      placeholder: ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://chiefmikey.github.io/CODE_OF_CONDUCT/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
