name: Auto-Merge

on: pull_request

permissions:
  contents: write

jobs:
  auto-merge:
    name: Auto-Merge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge "$PR_URL" --auto --squash --subject "$COMMIT_MESSAGE"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.DISPATCH_WORKFLOW}}
          COMMIT_MESSAGE: ${{github.event.pull_request.title}}
