name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Set Up
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install
      run: npm i

    - name: Run
      run: npm run gh-test

  test-v8:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Set Up
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install
      run: |
        npm i
        npm rm eslint
        npm i eslint@8

    - name: Run
      run: npm run gh-test-v8
